version: "3.9"

services:
  mssql-container:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Test@password

    ports:
      - "1433:1433"

    volumes:
      - mssql-container-data:/var/opt/mssql

volumes:
  mssql-container-data:
